[[mgr.prepend_keymap]]
on = "<Enter>"
run = "plugin smart-enter"
desc = "Enter directory or open file"

[[mgr.prepend_keymap]]
on = "o"
run = "plugin smart-enter"
desc = "Enter directory or open file"

[[mgr.prepend_keymap]]
on = "e"
run = "shell --block -- micro %h"
desc = "Edit with Micro"

[[mgr.prepend_keymap]]
on = "E"
run = "shell --block -- yazi-edit-right %h"
desc = "Edit with Micro in right pane"

[[mgr.prepend_keymap]]
on = [ "g", "u" ]
run = 'shell --orphan "gui-files \"$PWD\""'
desc = "Open GUI here"
