[opener]
enter_dir = [
  { run = "true", for = "unix", desc = "Use Enter to enter directory" },
]
edit = [
  { run = "micro %s", block = true, for = "unix", desc = "micro" },
]
image = [
  { run = "imv %s", orphan = true, for = "unix", desc = "imv" },
]
edit_image = [
  { run = "gimp %s", orphan = true, for = "unix", desc = "Edit with GIMP" },
]
media = [
  { run = "mpv -- %s", orphan = true, for = "unix", desc = "mpv" },
]
edit_video = [
  { run = "shotcut %s", orphan = true, for = "unix", desc = "Edit with Shotcut" },
]
browser = [
  { run = "helium-browser %s", orphan = true, for = "unix", desc = "Helium" },
]

[open]
prepend_rules = [
  { url = "*/", use = "enter_dir" },
  { url = "*.{html,htm}", use = "browser" },
  { mime = "application/pdf", use = "browser" },
  { url = "*.{txt,md,markdown,log,toml,lua,sh,bash,zsh,fish,conf,cfg,ini,json,jsonl,ndjson,yaml,yml,xml}", use = "edit" },
  { mime = "application/{json,ndjson,javascript,toml,yaml,x-yaml,xml}", use = "edit" },
  { mime = "text/*", use = "edit" },
  { mime = "image/*", use = ["image", "edit_image"] },
  { mime = "video/*", use = ["media", "edit_video"] },
  { mime = "audio/*", use = "media" },
]
