colors {
    background #003f7f
    statusline #ffffff
    separator  #ff9900

    focused_workspace  #ffcc00 #0055aa #ffffff
    active_workspace   #003f7f #003f7f #ffffff
    inactive_workspace #003f7f #003f7f #ffffff
    urgent_workspace   #ff4444 #ff4444 #ffffff
    binding_mode       #003f7f #003f7f #003f7f
}
