#!/usr/bin/env bash
set -Eeuo pipefail

export EDITOR="${EDITOR:-micro}"
export VISUAL="${VISUAL:-micro}"

if ! command -v zellij >/dev/null 2>&1; then
  exec /usr/bin/foot
fi

exec /usr/bin/foot zellij attach --create main
